# Generated by Django 3.2.8 on 2021-10-11 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('battery_installation_date', models.DateField()),
            ],
        ),
    ]
